### ISSUE TITLE
The --docdir parameter in the ./configure is invalid.

### ISSUE THREAD

**Issue by IXCIMAFW** [n42n/n3n#15]
Whether the `--docdir` parameter or the `DOCDIR` variable is specified, the default value (i.e. `/usr/share/doc/n3n`) remains unchanged..

**Comment by hamishcoleman** [comment]
Unfortunately, the configure script help output cannot be changed to indicate which paths are expected to work for any given project.

However, the --docdir should now work.  Please reopen if there are any issues
