### ISSUE TITLE
Traffic Restrictions on supernode?

### ISSUE THREAD

**Issue by crazyvest** [n42n/n3n#23]
Thanks for the codes.
Any way to config Traffic Restrictions on supernode server side? Traffic Restrictions could be configured in supernode or only edge?

**Comment by hamishcoleman** [comment]
The Supernode can control which community names and/or require a username and password to allow edges to join.  However, once an edge has joined the network, it will try and send VPN traffic directly to its peers, so the supernode cannot be involved in filtering the regular traffic.

What are you trying to achieve?  Perhaps we could suggest a way of doing it.

**Comment by crazyvest** [comment]
For security and bandwidth control, it is desirable to configure traffic restriction rules on supernode server, Send mandatory rules to edges.  hope the traffic restriction commond "filter.rule" could be used in supernode.

**Comment by hamishcoleman** [comment]
That sounds like an interesting feature.  There would be come caveats though as the edges are expected to be under the control of the person running them, so there wouldnt really be any way to make such rules mandatory.

**Comment by starvpn** [comment]
What he meant should be the inability to connect directly to P2P and the traffic restrictions when forwarding through supernode

**Comment by hamishcoleman** [comment]
If I understand you correctly, it sounds like you are looking for a way to turn off all P2P functionality and at the same time add a firewall rule engine to the supernode - is that correct?

You realise that those are some of the key differentiating features for this VPN compared to others?

**Comment by crazyvest** [comment]
yes, that's what sarvpn said.

**Comment by hamishcoleman** [comment]
One major technical barrier to implementing a normal firewall rule set in the supernode is that the supernode has no access to the packet contents - it just sees the encrypted data and the randomised MAC addresses.

**Comment by NiKola-UE** [comment]
Unfortunately, I'm not a programmer, but maybe 
[Nymtech's Nym ](https://github.com/nymtech/nym) 
can be used for this, which I guess is exactly what it's for, i.e. prevents a decryption attempt.
