### ISSUE TITLE
Can you add some features?

### ISSUE THREAD

**Issue by moqiu365** [n42n/n3n#39]
1. Can the boss add port access restrictions between nodes? For example, I hope that user A cannot access user B's 3389 remote port and only allow access to the 80 port that I specify can be accessed?
2. I hope the boss can compile an IPK version that supports arm64. I have a soft router for arm64, but I don't see any IPK files that support arm64 in the branch file

**Comment by hamishcoleman** [comment]
Translated to English:
> 1. Can you add port access restrictions between nodes? For example, I hope that user A cannot access user B's 3389 remote port, and only allows access to port 80 that I specify to be accessible?
> 2. I hope you can compile an ipk version that supports arm64. I have an arm64 soft router, and I see that the branch file does not have an ipk file that supports arm64.

(Please remember that the language used for maintaining this project is English)

**Comment by moqiu365** [comment]
> Translated to English:
> 
> > 1. Can you add port access restrictions between nodes? For example, I hope that user A cannot access user B's 3389 remote port, and only allows access to port 80 that I specify to be accessible?
> > 2. I hope you can compile an ipk version that supports arm64. I have an arm64 soft router, and I see that the branch file does not have an ipk file that supports arm64.
> 
> (Please remember that the language used for maintaining this project is English)

OK，I have adjusted the reply content, can you see if it can be implemented?

**Comment by hamishcoleman** [comment]
1. The most reliable and well documented way to add restrictions is to use the firewall rules built into your operating system.  There is a filtering feature in n3n, but it is not nearly as well tested as the OS built-in firewall, nor is it a performant or flexible either.
2. It should be straight forward to add an openwrt arm64 build to the CI.  I am travelling at the moment, so I might not have an opportunity to try that for a couple of days.

**Comment by moqiu365** [comment]
> 1. The most reliable and well documented way to add restrictions is to use the firewall rules built into your operating system.  There is a filtering feature in n3n, but it is not nearly as well tested as the OS built-in firewall, nor is it a performant or flexible either.
> 2. It should be straight forward to add an openwrt arm64 build to the CI.  I am travelling at the moment, so I might not have an opportunity to try that for a couple of days.
1.Thank you, but what I'm thinking is, if I have a game server for node A and a player's own computer for node B (with many player B-Zs), for data security, how can I prevent players from accessing services on other player nodes and only allow the ports I set to access each other?
2.Okay, the supernode program has not been compiled into the deb package. I hope it can be compiled

**Comment by hamishcoleman** [comment]
Since the core feature of this vpn is to be peer-to-peer, there is not really a way to restrict traffic from traveling between peers.

**Comment by hamishcoleman** [comment]
> 2.Okay, the supernode program has not been compiled into the deb package. I hope it can be compiled

I'm not sure I understand what you are saying here - the supernode program is definitely in all the deb packages that are created by the CI system

**Comment by moqiu365** [comment]
> > 2.Okay, the supernode program has not been compiled into the deb package. I hope it can be compiled
> 
> I'm not sure I understand what you are saying here - the supernode program is definitely in all the deb packages that are created by the CI system

Okay, I understand. I really didn't see the deb package for supernode in Releases, only n3n-3.3.4-1uamd64.deb and n3n build deps1.0 all. Deb. Do these two packages integrate supernode?

**Comment by hamishcoleman** [comment]
Currently, there is only one deb file created, containing both the supernode and the edge programs.  This may be split up in the future (like the ipk packages)

**Comment by moqiu365** [comment]
> Currently, there is only one deb file created, containing both the supernode and the edge programs. This may be split up in the future (like the ipk packages)

Okay, I understand. Thank you
