### ISSUE TITLE
edge running,but has warning :"WARNING: n3n has not been compiled with libcap-dev; some commands may fail"

### ISSUE THREAD

**Issue by xiacc-cn** [n42n/n3n#41]
![image](https://github.com/n42n/n3n/assets/82486481/c538247c-a32d-4afa-bc89-fece65393016)
./autogen.sh
./configure
make

**Comment by hamishcoleman** [comment]
This benign informational message needs to be adjusted for better clarity in a future release.

It is simply informing you that the binary was not compiled with support for one of the optional features.  In the end, I do not believe that any of these possible other commands have ever failed, so the message can be updated with that knowledge

**Comment by hamishcoleman** [comment]
This message has been updated in d658ec75fddf to try and make it less confusing
