### ISSUE TITLE
Can DHCP be added and placed in the same group, and edge can customize subnet masks?

### ISSUE THREAD

**Issue by moqiu365** [n42n/n3n#42]
For example, SuperNode sets the minimum IP range to 10.50.0.0 and the maximum IP range to 10.50.255.255
Edge A user sets IP to 10.50.60.1 and group to test
Edge B user group is test, but IP is not automatically obtained
If user B is assigned to another network segment, such as 10.50.70.1, then user B will not be able to access user A unless the subnet mask is manually set to 255.255.0.0. To manually set user B to the same group network segment, such as 10.50.60.100, mutual access can only be made at this time
I hope to customize the subnet mask when set to automatic acquisition

**Comment by moqiu365** [comment]
> I'm not sure if I fully understand what you are trying to achieve.
> 
> The exact subnet used for auto addresses to assign to each community can be set by using the community list file when configuring the supernode.
> 
> If you need to vary the automatically used subnet length, this is defined by the subnet length used when specifying the value of supernode.auto_ip_min
> 
> If you do not specify an exact subnet in the community list, then the supernode will calculate a subnet and use it - this may vary from time to time depending on other edges or exactly which communities in use, so it is best not to rely on it.
> 
> (None of this is DHCP, but you could also simply provision a DHCP server with access to the community and configure any number of more complex settings using that)

Can you specify the Edge parameters and manually set the subnet mask of the network card? For example, - O SubMark=255.255.255.0
Then it will automatically set the subnet mask of the network card to 255.255.255.0

**Comment by hamishcoleman** [comment]
When statically setting the edge ip address, you can specify the subnet length by appending a "/" and then length - eg tuntap.address=10.55.100.5/24

If the automatic address assignment is being used, then this subnet length cannot be easily set by the edge - it needs to be set using the supernode community list file as mentioned above.

In all cases, the network interface can simply be reconfigured using the normal operating system commands, so you could always change the subnet details with a script
