### ISSUE TITLE
How is this different from n2n?

### ISSUE THREAD

**Issue by YCJDWCJI** [n42n/n3n#7]
Does it mean that [n2n] stops updating?

[n2n]: https://github.com/ntop/n2n

**Comment by hamishcoleman** [comment]
There have been recent changes to the licensing arrangements in the n2n project that make some of the contributors uncomfortable.

It is hoped that discussions can change the license for the original n2n repo to address those concerns.  This repository is a fork from immediately prior to those changes, that allows further development and improvements without being affected by the license changes.

**Comment by eebssk1** [comment]
Are there any milestone or future plan on implementing highly demanding new features like p2p-via-ipv6 and FEC?

**Comment by hamishcoleman** [comment]
Hi @eebssk1 , yes, there are definitely future plans.  However work has been focused on getting the API changes stable and ready for the first release.

The IPv6 support is waiting for me to get a native IPv6 connection to test things with.  Evaluating adding FEC requires some metrics to determine how often packets are being lost (and why) - if the packets are not being lost then FEC adds no value and if the packets are being lost due to minor issues with the protocol then fixing the protocol would provide better value than adding FEC

**Comment by eebssk1** [comment]
> Hi @eebssk1 , yes, there are definitely future plans.  However work has been focused on getting the API changes stable and ready for the first release.
> 
> The IPv6 support is waiting for me to get a native IPv6 connection to test things with.  Evaluating adding FEC requires some metrics to determine how often packets are being lost (and why) - if the packets are not being lost then FEC adds no value and if the packets are being lost due to minor issues with the protocol then fixing the protocol would provide better value than adding FEC

It's good to hear that.

BTW pls check https://github.com/ntop/n2n/issues/1165
Though I'm not having the problem now,seems like a edge case.

**Comment by hamishcoleman** [comment]
There have been significant code changes since your debugging, so if you can reproduce it with the n3n code, then that would make investigations possible.

**Comment by eebssk1** [comment]
> There have been significant code changes since your debugging, so if you can reproduce it with the n3n code, then that would make investigations possible.
> 

I will check later. But I suppose the GUI does not support N3N since there are comandline handling changes?

**Comment by hamishcoleman** [comment]
I've never used that GUI or looked at their code, so I'm not the right person to ask.

However - yes, the CLI has been almost completely changed (To improve consistency and simplify things for users - so if they were building their GUI again today, they would probably find it easier to do)
